on: pull_request
jobs:
  block-drafts:
    name: block-drafts
    if: github.base_ref == 'main'
    runs-on: docker
    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: investigate
        run: |
          pwd
          echo ===
          ls -lash
          echo ===
          git status
          echo ===
          ls -lash automation
      - name: block-drafts
        run: make check-no-drafts
