on: pull_request
jobs:
  block-drafts:
    name: block-drafts
    if: github.base_ref == 'main'
    runs-on: docker
    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: block-drafts
        run: |
          drafts=$(make find-drafts)
          n_drafts=$(echo "$drafts" | wc -l)
          if [ $n_drafts -gt 0 ]; then
            echo "Failure: can't merge draft posts into main. See the list below:"
            echo "$drafts"
            exit 1
          fi
          echo "Success!"
