on: pull_request
jobs:
  block-drafts:
    name: block-drafts
    if: github.base_ref == 'main'
    runs-on: docker
    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: block-drafts
        run: |
          if [ make find-drafts ]; then exit 1; fi
          echo "Success!"
