on: [push]
jobs:
  quality:
    name: code-quality
    runs-on: docker
    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: setup uv
        uses: https://github.com/astral-sh/setup-uv@v6
        with:
          enable-cache: true
          prune-cache: false
      - name: run ShellCheck
        run: make check-scripts
      - name: run pre-commit checks
        run: SKIP="shellcheck,no-commit-to-branch" make check-precommit
  build:
    name: build
    needs: quality
    runs-on: docker
    steps:
      - name: checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: setup uv
        uses: https://github.com/astral-sh/setup-uv@v6
        with:
          enable-cache: true
          prune-cache: false
      - name: build
        run: make publish
      - name: upload-artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: web-content-${{ github.sha }}
          path: |
            output/
            !**/.gitkeep
          if-no-files-found: error
  deploy:
    name: deploy
    needs: build
    # if: github.ref == 'refs/heads/main'
    runs-on: docker
    steps:
      - name: download-artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          name: web-content-${{ github.sha }}
          path: output
      - name: setup rsync
        id: rsync
        run: |
          apt-get -qq update
          apt-get -qq install rsync
          (umask 077 && touch deploy_id)
          echo "${{ secrets.DEPLOY_KEY }}" > deploy_id
          echo "${{ secrets.DEPLOY_KNOWN_HOSTS }}" >> /etc/ssh/ssh_known_hosts
      - name: deploy
        run: |
          rsync -rvz --delete -e "ssh -i deploy_id" output/ \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_TARGET_DIR }}
